// <auto-generated />
using LakeLabRemote.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LakeLabRemote.Migrations.ValuesDb
{
    [DbContext(typeof(ValuesDbContext))]
    [Migration("20170924114229_Values")]
    partial class Values
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("LakeLabRemote.Models.Device", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Depth");

                    b.Property<string>("Ip");

                    b.Property<string>("Location");

                    b.HasKey("Name");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("LakeLabRemote.Models.ValueDO", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceName");

                    b.Property<DateTime>("Timestamp");

                    b.Property<int>("Value");

                    b.HasKey("Guid");

                    b.HasIndex("DeviceName");

                    b.ToTable("ValuesDO");
                });

            modelBuilder.Entity("LakeLabRemote.Models.ValueDO", b =>
                {
                    b.HasOne("LakeLabRemote.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceName");
                });
#pragma warning restore 612, 618
        }
    }
}
